plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - spec/app/**/*
    - spec/schemas/**/*
    - spec/snapshots/**/*

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Max: 120

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Lint/UnusedBlockArgument:
  AllowUnusedKeywordArguments: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/MissingSuper:
  Enabled: false

Metrics:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/IfUnlessModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'

Style/RedundantSelf:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  EnforcedStyle: percent

RSpec/ExampleWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false
