# frozen_string_literal: true

require 'avro_gen/upgrader'
require 'fileutils'

RSpec.describe AvroGen::Upgrader do
  describe '.rewrite' do
    it 'rewrites the Deimos schema-class superclasses' do
      expect(described_class.rewrite('class Foo < Deimos::SchemaClass::Record')).
        to eq('class Foo < AvroGen::SchemaClass::Record')
      expect(described_class.rewrite('class E < Deimos::SchemaClass::Enum')).
        to eq('class E < AvroGen::SchemaClass::Enum')
    end

    it 'rewrites the Deimos::Utils::SchemaClass helper' do
      expect(described_class.rewrite('Deimos::Utils::SchemaClass.instance({}, "Foo")')).
        to eq('AvroGen::SchemaClass.instance({}, "Foo")')
    end

    it 'rewrites the autogenerated-by header' do
      expect(described_class.rewrite('# This file is autogenerated by Deimos, Do NOT modify')).
        to eq('# This file is autogenerated by AvroGen, Do NOT modify')
    end

    it 'leaves already-migrated content untouched' do
      content = "# This file is autogenerated by AvroGen, Do NOT modify\nclass Foo < AvroGen::SchemaClass::Record\nend\n"
      expect(described_class.rewrite(content)).to eq(content)
    end
  end

  describe '.run' do
    let(:dir) { 'spec/app/upgrade' }

    before(:each) do
      FileUtils.mkdir_p(dir)
      File.write("#{dir}/foo.rb", <<~RUBY)
        # This file is autogenerated by Deimos, Do NOT modify
        module Schemas
          class Foo < Deimos::SchemaClass::Record; end
        end
      RUBY
      File.write("#{dir}/already.rb", "class Bar < AvroGen::SchemaClass::Record; end\n")
    end

    after(:each) do
      FileUtils.rm_rf('spec/app')
    end

    it 'rewrites files that need it and returns them' do
      changed = described_class.run(path: dir)
      expect(changed).to eq(["#{dir}/foo.rb"])
      expect(File.read("#{dir}/foo.rb")).to include('autogenerated by AvroGen', 'AvroGen::SchemaClass::Record')
      expect(File.read("#{dir}/foo.rb")).not_to include('Deimos')
    end
  end
end
