# frozen_string_literal: true

require_relative 'configuration'

module AvroGen
  # Rewrites references in checked-in generated schema-class files from the old
  # Deimos constants to their AvroGen equivalents, so users can migrate off the
  # deprecated `const_missing` fallback in one shot.
  module Upgrader
    REPLACEMENTS = {
      'Deimos::SchemaClass::Record' => 'AvroGen::SchemaClass::Record',
      'Deimos::SchemaClass::Enum' => 'AvroGen::SchemaClass::Enum',
      'Deimos::SchemaClass::Base' => 'AvroGen::SchemaClass::Base',
      'Deimos::Utils::SchemaClass' => 'AvroGen::SchemaClass',
      # The autogenerated-by header that older Deimos-generated files carry.
      'autogenerated by Deimos' => 'autogenerated by AvroGen'
    }.freeze

    class << self
      # @param path [String] directory containing generated classes; defaults to config
      # @return [Array<String>] the list of files that were rewritten
      def run(path: nil)
        path ||= AvroGen.config.generated_class_path
        changed = []
        Dir["#{path}/**/*.rb"].each do |file|
          original = File.read(file)
          updated = rewrite(original)
          next if updated == original

          File.write(file, updated)
          changed << file
        end
        changed
      end

      # @param contents [String]
      # @return [String]
      def rewrite(contents)
        REPLACEMENTS.reduce(contents) do |text, (from, to)|
          text.gsub(from, to)
        end
      end
    end
  end
end
